language: php

php:
  - 7.2
  - nightly
  - hhvm

matrix:
  allow_failures:
    - php: nightly
    - php: hhvm

before_script:
  - composer install --dev --prefer-dist -o

script:
  # - ./vendor/bin/phpunit --coverage-clover tmp/clover.xml
  - ./vendor/bin/phing

# after_success:
  # - ./vendor/bin/test-reporter --coverage-report tmp/clover.xml
