language: php

php:
  - 7.2
  - nightly
  - hhvm

matrix:
  allow_failures:
    - php: nightly
    - php: hhvm

before_script:
  - composer install --dev --prefer-dist -o
#   - composer require --dev codeclimate/php-test-reporter

script:
#   - ./vendor/bin/phing
  - ./vendor/bin/phpunit --coverage-clover tmp/clover.xml

# after_success:
#   - ./vendor/bin/test-reporter --coverage-report tmp/clover.xml
